// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: plugin.proto

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeshPlugin_PluginInfo_FullMethodName  = "/meshplugin.MeshPlugin/PluginInfo"
	MeshPlugin_HealthCheck_FullMethodName = "/meshplugin.MeshPlugin/HealthCheck"
	MeshPlugin_GetAdapter_FullMethodName  = "/meshplugin.MeshPlugin/GetAdapter"
)

// MeshPluginClient is the client API for MeshPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeshPluginClient interface {
	PluginInfo(ctx context.Context, in *PluginMetaRequest, opts ...grpc.CallOption) (*PluginMetaResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	GetAdapter(ctx context.Context, in *GetAdapterRequest, opts ...grpc.CallOption) (*GetAdapterResponse, error)
}

type meshPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewMeshPluginClient(cc grpc.ClientConnInterface) MeshPluginClient {
	return &meshPluginClient{cc}
}

func (c *meshPluginClient) PluginInfo(ctx context.Context, in *PluginMetaRequest, opts ...grpc.CallOption) (*PluginMetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginMetaResponse)
	err := c.cc.Invoke(ctx, MeshPlugin_PluginInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshPluginClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, MeshPlugin_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshPluginClient) GetAdapter(ctx context.Context, in *GetAdapterRequest, opts ...grpc.CallOption) (*GetAdapterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdapterResponse)
	err := c.cc.Invoke(ctx, MeshPlugin_GetAdapter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeshPluginServer is the server API for MeshPlugin service.
// All implementations must embed UnimplementedMeshPluginServer
// for forward compatibility.
type MeshPluginServer interface {
	PluginInfo(context.Context, *PluginMetaRequest) (*PluginMetaResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	GetAdapter(context.Context, *GetAdapterRequest) (*GetAdapterResponse, error)
	mustEmbedUnimplementedMeshPluginServer()
}

// UnimplementedMeshPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeshPluginServer struct{}

func (UnimplementedMeshPluginServer) PluginInfo(context.Context, *PluginMetaRequest) (*PluginMetaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PluginInfo not implemented")
}
func (UnimplementedMeshPluginServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMeshPluginServer) GetAdapter(context.Context, *GetAdapterRequest) (*GetAdapterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdapter not implemented")
}
func (UnimplementedMeshPluginServer) mustEmbedUnimplementedMeshPluginServer() {}
func (UnimplementedMeshPluginServer) testEmbeddedByValue()                    {}

// UnsafeMeshPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeshPluginServer will
// result in compilation errors.
type UnsafeMeshPluginServer interface {
	mustEmbedUnimplementedMeshPluginServer()
}

func RegisterMeshPluginServer(s grpc.ServiceRegistrar, srv MeshPluginServer) {
	// If the following call panics, it indicates UnimplementedMeshPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeshPlugin_ServiceDesc, srv)
}

func _MeshPlugin_PluginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshPluginServer).PluginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshPlugin_PluginInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshPluginServer).PluginInfo(ctx, req.(*PluginMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshPlugin_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshPluginServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshPlugin_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshPluginServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshPlugin_GetAdapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshPluginServer).GetAdapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshPlugin_GetAdapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshPluginServer).GetAdapter(ctx, req.(*GetAdapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeshPlugin_ServiceDesc is the grpc.ServiceDesc for MeshPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeshPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meshplugin.MeshPlugin",
	HandlerType: (*MeshPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PluginInfo",
			Handler:    _MeshPlugin_PluginInfo_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _MeshPlugin_HealthCheck_Handler,
		},
		{
			MethodName: "GetAdapter",
			Handler:    _MeshPlugin_GetAdapter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
