// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: plugin.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginMetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginMetaRequest) Reset() {
	*x = PluginMetaRequest{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMetaRequest) ProtoMessage() {}

func (x *PluginMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMetaRequest.ProtoReflect.Descriptor instead.
func (*PluginMetaRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type PluginMetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginMetaResponse) Reset() {
	*x = PluginMetaResponse{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMetaResponse) ProtoMessage() {}

func (x *PluginMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMetaResponse.ProtoReflect.Descriptor instead.
func (*PluginMetaResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginMetaResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginMetaResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginMetaResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginMetaResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAdapterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdapterRequest) Reset() {
	*x = GetAdapterRequest{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdapterRequest) ProtoMessage() {}

func (x *GetAdapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdapterRequest.ProtoReflect.Descriptor instead.
func (*GetAdapterRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

type GetAdapterResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SubstrateName   string                 `protobuf:"bytes,1,opt,name=substrate_name,json=substrateName,proto3" json:"substrate_name,omitempty"`
	SupportsExport  bool                   `protobuf:"varint,2,opt,name=supports_export,json=supportsExport,proto3" json:"supports_export,omitempty"`
	SupportsImport  bool                   `protobuf:"varint,3,opt,name=supports_import,json=supportsImport,proto3" json:"supports_import,omitempty"`
	SupportsInspect bool                   `protobuf:"varint,4,opt,name=supports_inspect,json=supportsInspect,proto3" json:"supports_inspect,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAdapterResponse) Reset() {
	*x = GetAdapterResponse{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdapterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdapterResponse) ProtoMessage() {}

func (x *GetAdapterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdapterResponse.ProtoReflect.Descriptor instead.
func (*GetAdapterResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *GetAdapterResponse) GetSubstrateName() string {
	if x != nil {
		return x.SubstrateName
	}
	return ""
}

func (x *GetAdapterResponse) GetSupportsExport() bool {
	if x != nil {
		return x.SupportsExport
	}
	return false
}

func (x *GetAdapterResponse) GetSupportsImport() bool {
	if x != nil {
		return x.SupportsImport
	}
	return false
}

func (x *GetAdapterResponse) GetSupportsInspect() bool {
	if x != nil {
		return x.SupportsInspect
	}
	return false
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\n" +
	"meshplugin\"\x13\n" +
	"\x11PluginMetaRequest\"|\n" +
	"\x12PluginMetaResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\"\x14\n" +
	"\x12HealthCheckRequest\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11GetAdapterRequest\"\xb8\x01\n" +
	"\x12GetAdapterResponse\x12%\n" +
	"\x0esubstrate_name\x18\x01 \x01(\tR\rsubstrateName\x12'\n" +
	"\x0fsupports_export\x18\x02 \x01(\bR\x0esupportsExport\x12'\n" +
	"\x0fsupports_import\x18\x03 \x01(\bR\x0esupportsImport\x12)\n" +
	"\x10supports_inspect\x18\x04 \x01(\bR\x0fsupportsInspect2\xf6\x01\n" +
	"\n" +
	"MeshPlugin\x12K\n" +
	"\n" +
	"PluginInfo\x12\x1d.meshplugin.PluginMetaRequest\x1a\x1e.meshplugin.PluginMetaResponse\x12N\n" +
	"\vHealthCheck\x12\x1e.meshplugin.HealthCheckRequest\x1a\x1f.meshplugin.HealthCheckResponse\x12K\n" +
	"\n" +
	"GetAdapter\x12\x1d.meshplugin.GetAdapterRequest\x1a\x1e.meshplugin.GetAdapterResponseB:Z8github.com/rethink-paradigms/mesh/internal/plugin;pluginb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_plugin_proto_goTypes = []any{
	(*PluginMetaRequest)(nil),   // 0: meshplugin.PluginMetaRequest
	(*PluginMetaResponse)(nil),  // 1: meshplugin.PluginMetaResponse
	(*HealthCheckRequest)(nil),  // 2: meshplugin.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: meshplugin.HealthCheckResponse
	(*GetAdapterRequest)(nil),   // 4: meshplugin.GetAdapterRequest
	(*GetAdapterResponse)(nil),  // 5: meshplugin.GetAdapterResponse
}
var file_plugin_proto_depIdxs = []int32{
	0, // 0: meshplugin.MeshPlugin.PluginInfo:input_type -> meshplugin.PluginMetaRequest
	2, // 1: meshplugin.MeshPlugin.HealthCheck:input_type -> meshplugin.HealthCheckRequest
	4, // 2: meshplugin.MeshPlugin.GetAdapter:input_type -> meshplugin.GetAdapterRequest
	1, // 3: meshplugin.MeshPlugin.PluginInfo:output_type -> meshplugin.PluginMetaResponse
	3, // 4: meshplugin.MeshPlugin.HealthCheck:output_type -> meshplugin.HealthCheckResponse
	5, // 5: meshplugin.MeshPlugin.GetAdapter:output_type -> meshplugin.GetAdapterResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
